[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.12.79"

[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
